### ISSUE TITLE
Epic: Review Letter

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#107]
User Flow: 
Once user has [authenticated](#17), routes are opened to review letter, send letter, and add any donations

<img width="1031" alt="Screen Shot 2021-09-07 at 3 27 02 PM" src="https://user-images.githubusercontent.com/9143339/132781300-113244f8-8a3e-4230-b80b-2a144131ac4b.png">

These backend functions use the API endpoints from Lob and Stripe. We are able to perform the folllowing functions: 
- review letter
  - [x] letter displayed: use get function to show contents of letter 
  - [ ] customizeable message: frontend caches message to append
  - [ ] append letter if there is a custom message : use append function to send new version of letter
