### ISSUE TITLE
Epic: Apple Pay

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#185]
- [ ] route Apple Pay 
   - [ ] Integrate via secret in heroku 
   - [ ] Have a test API for devs
 - [ ] integrate in our checkout function 
 - [ ] Write unit tests
 - [ ] Write API tests
