### ISSUE TITLE
Epic: Codespaces Frontend

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#203]
- [ ] set up default container configuration
- [ ] Adding additional features to your devcontainer.json file
- [ ] Adding custom codespace configurations

### Context
A development container, or dev container, is the environment that Codespaces uses to provide the tools and runtimes that your project needs for development. If your project does not already have a dev container defined, Codespaces will use the default configuration, which contains many of the common tools that your team might need for development with your project. 

Codespaces allows for customization on a per-project and per-branch basis with a devcontainer.json file. This configuration file determines the environment of every new codespace anyone creates for your repository by defining a development container that can include frameworks, tools, extensions, and port forwarding. A Dockerfile can also be used alongside the devcontainer.json file in the .devcontainer folder to define everything required to create a container image.
